# Generated by Django 5.0.6 on 2024-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_anime_is_active_anime_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='animemovie',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
