# Generated by Django 5.0.6 on 2024-07-14 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_anime_name_alter_animemovie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('age', models.IntegerField()),
                ('info', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('anime_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.animemovie')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
    ]
