# Generated by Django 5.0.6 on 2024-07-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_animecharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/'),
        ),
    ]
